# Generated by Django 4.0.3 on 2022-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='external_link',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
